name: Life Quest CI/CD

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create appsettings.json
        run: |
          echo '{"GeminiApiKey": "${{ secrets.GEMINI_API_KEY }}"}' > src/LifeQuest.Presentation/appsettings.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Check Code Formatting
        run: dotnet format src/LifeQuest.slnx --verify-no-changes
        continue-on-error: true

      - name: Restore dependencies
        run: dotnet restore src/LifeQuest.slnx

      - name: Build project
        run: dotnet build src/LifeQuest.slnx --configuration Release --no-restore

      - name: Run automated tests
        run: dotnet test src/LifeQuest.slnx --configuration Release --no-build --verbosity normal

      # - name: Pack Domain for GitHub Packages
      #  if: startsWith(github.ref, 'refs/tags/v')
      #  run: dotnet pack src/LifeQuest.Domain/LifeQuest.Domain.csproj -c Release -o ./nuget_packages

      # - name: Publish to GitHub Packages
      #   if: startsWith(github.ref, 'refs/tags/v')
      #  run: dotnet nuget push ./nuget_packages/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Windows App
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: dotnet publish src/LifeQuest.Presentation/LifeQuest.Presentation.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish_output

      - name: Upload Build Artifact
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        uses: actions/upload-artifact@v4
        with:
          name: LifeQuest-Windows-Build
          path: ./publish_output/

  release:
    needs: build-and-test
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    permissions:
      contents: write
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: LifeQuest-Windows-Build
          path: ./publish_output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Life Quest ${{ github.ref_name }}"
          body: |
            ## 🏰 Life Quest ${{ github.ref_name }}
            - Нова версія гри автоматично зібрана та готова до завантаження!
            - Ядро системи також опубліковано у GitHub Packages.
          files: ./publish_output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}